/* Generated By:JavaCC: Do not edit this line. BibtextGrammarConstants.java */
package gramatica;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BibtextGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LB = 5;
  /** RegularExpression Id. */
  int RB = 6;
  /** RegularExpression Id. */
  int ARTICLE = 7;
  /** RegularExpression Id. */
  int BOOK = 8;
  /** RegularExpression Id. */
  int BOOKLET = 9;
  /** RegularExpression Id. */
  int CONFERENCE = 10;
  /** RegularExpression Id. */
  int INBOOK = 11;
  /** RegularExpression Id. */
  int INCOLLECTION = 12;
  /** RegularExpression Id. */
  int INPROCEEDINGS = 13;
  /** RegularExpression Id. */
  int MANUAL = 14;
  /** RegularExpression Id. */
  int MASTERSTHESIS = 15;
  /** RegularExpression Id. */
  int MISC = 16;
  /** RegularExpression Id. */
  int PHDTHESIS = 17;
  /** RegularExpression Id. */
  int PROCEEDINGS = 18;
  /** RegularExpression Id. */
  int TECHREPORT = 19;
  /** RegularExpression Id. */
  int UNPUBLISHED = 20;
  /** RegularExpression Id. */
  int AUTHOR = 21;
  /** RegularExpression Id. */
  int JOURNAL = 22;
  /** RegularExpression Id. */
  int TITLE = 23;
  /** RegularExpression Id. */
  int YEAR = 24;
  /** RegularExpression Id. */
  int MONTH = 25;
  /** RegularExpression Id. */
  int NUMBER = 26;
  /** RegularExpression Id. */
  int PAGES = 27;
  /** RegularExpression Id. */
  int VOLUME = 28;
  /** RegularExpression Id. */
  int PUBLISHER = 29;
  /** RegularExpression Id. */
  int DOI = 30;
  /** RegularExpression Id. */
  int NOTE = 31;
  /** RegularExpression Id. */
  int KEY = 32;
  /** RegularExpression Id. */
  int EDITOR = 33;
  /** RegularExpression Id. */
  int SERIES = 34;
  /** RegularExpression Id. */
  int ADDRESS = 35;
  /** RegularExpression Id. */
  int EDITION = 36;
  /** RegularExpression Id. */
  int URL = 37;
  /** RegularExpression Id. */
  int HOWPUBLISHED = 38;
  /** RegularExpression Id. */
  int CHAPTER = 39;
  /** RegularExpression Id. */
  int BOOKTITLE = 40;
  /** RegularExpression Id. */
  int TYPE = 41;
  /** RegularExpression Id. */
  int ORGANIZATION = 42;
  /** RegularExpression Id. */
  int SCHOOL = 43;
  /** RegularExpression Id. */
  int INSTITUTION = 44;
  /** RegularExpression Id. */
  int WORD = 45;
  /** RegularExpression Id. */
  int CONSTANT = 46;
  /** RegularExpression Id. */
  int ID = 47;
  /** RegularExpression Id. */
  int LETTERSNUMBERS = 48;
  /** RegularExpression Id. */
  int LETTER = 49;
  /** RegularExpression Id. */
  int LOWER = 50;
  /** RegularExpression Id. */
  int UPPER = 51;
  /** RegularExpression Id. */
  int DIGIT = 52;
  /** RegularExpression Id. */
  int COMMA = 53;
  /** RegularExpression Id. */
  int SEMICOLON = 54;
  /** RegularExpression Id. */
  int DASH = 55;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"{\"",
    "\"}\"",
    "\"article\"",
    "\"book\"",
    "\"booklet\"",
    "\"conference\"",
    "\"inbook\"",
    "\"incollection\"",
    "\"inproceedings\"",
    "\"manual\"",
    "\"mastersthesis\"",
    "\"misc\"",
    "\"phdthesis\"",
    "\"proceedings\"",
    "\"techreport\"",
    "\"unpublished\"",
    "\"Author\"",
    "\"Journal\"",
    "\"Title\"",
    "\"Year\"",
    "\"Month\"",
    "\"Number\"",
    "\"Pages\"",
    "\"Volume\"",
    "\"Publisher\"",
    "\"Doi\"",
    "\"Note\"",
    "\"Key\"",
    "\"Editor\"",
    "\"Series\"",
    "\"Address\"",
    "\"Edition\"",
    "\"Url\"",
    "\"Howpublished\"",
    "\"Chapter\"",
    "\"Booktitle\"",
    "\"Type\"",
    "\"Organization\"",
    "\"School\"",
    "\"Institution\"",
    "<WORD>",
    "<CONSTANT>",
    "<ID>",
    "<LETTERSNUMBERS>",
    "<LETTER>",
    "<LOWER>",
    "<UPPER>",
    "<DIGIT>",
    "<COMMA>",
    "<SEMICOLON>",
    "<DASH>",
    "\"@\"",
    "\"=\"",
    "\"-\"",
    "\".\"",
    "\",\"",
    "\"\\\'\"",
    "\":\"",
    "\"/\"",
  };

}
